import Nav from '@/components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footter from '@/components/Footter'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Online contact store",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      type: "image/jpg",
      sizes: "32x32",
      url: "/images.png",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-[100vh]'>
          <Nav />
          <div> {children}</div>
          <Footter />
        </div>
       
      </body>
    </html>
  )
}
