import Nav from '@/components/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footter from '@/components/Footter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Online contact store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-[100vh]'>
          <Nav />
          <div> {children}</div>
          <Footter />
        </div>
       
      </body>
    </html>
  )
}
